/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  iban?: string;
  active?: boolean;
  email: string;
  firstName: string;
  id?: number;
  lastName: string;
  password: string;
}
